version: "3"
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.9.25-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq/:/var/lib/rabbitmq/
    networks:
      - rabbitmq_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 5

  inference:
    build: ./ml/
    environment:
      - RABBITMQ_HOST=rabbitmq
      - INFERENCE_EXCHANGE_NAME=inference
      - WEIGHTS_PATH=/app/weights/densenet121.h5
      - API_URL=http://app:5000
      - API_USER=inference
      - API_PASSWORD=d38a068fd7943a39c6feef268f065e5132eb9d3328485339f6d81b282d2e235a
    volumes:
      - ./ml/weights/:/app/weights/:ro
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net
      - api_net

  app:
    hostname: app
    build: ./api/
    environment:
      - RABBITMQ_HOST=rabbitmq
      - INFERENCE_EXCHANGE_NAME=inference
      - UPLOAD_FOLDER=static
    ports:
      - 4999:5000
    volumes:
      - ./api/:/app/
      # - ./api/static:/app/static
    networks:
      - mysql_net
      - api_net
      - rabbitmq_net

  db:
    image: mysql:8.0.30
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - mysql_net
    
networks:
  rabbitmq_net:
    driver: bridge

  mysql_net:
    driver: bridge

  api_net:
    driver: bridge