version: "3"
services:
  app:
    build: .
    ports:
      - 5090:5000
    volumes:
      - .:/app:ro
    networks:
      - db

  db:
    image: mysql:8.0.30
    hostname: db
    ports:
      - 30000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - db

networks:
  db:
    driver: bridge